# Generated by Django 4.1.6 on 2023-02-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Topics",
            new_name="Topic",
        ),
    ]
